(cl:in-package hehe-msg)
(cl:export '(NUMBER-VAL
          NUMBER
          ANGLE_MIN-VAL
          ANGLE_MIN
          ANGLE_MAX-VAL
          ANGLE_MAX
          ANGLE_INC-VAL
          ANGLE_INC
          TIME_INC-VAL
          TIME_INC
          SCAN_TIME-VAL
          SCAN_TIME
          RANGE_MIN-VAL
          RANGE_MIN
          RANGE_MAX-VAL
          RANGE_MAX
          RANGE_SIZE-VAL
          RANGE_SIZE
          COUNT-VAL
          COUNT
          COUNTLESS-VAL
          COUNTLESS
          LIDAR_RANGES_1-VAL
          LIDAR_RANGES_1
          LIDAR_RANGES_2-VAL
          LIDAR_RANGES_2
          LIDAR_RANGES_3-VAL
          LIDAR_RANGES_3
          LIDAR_RANGES_4-VAL
          LIDAR_RANGES_4
          LIDAR_RANGES_5-VAL
          LIDAR_RANGES_5
          LIDAR_RANGES_6-VAL
          LIDAR_RANGES_6
          LIDAR_RANGES_7-VAL
          LIDAR_RANGES_7
          LIDAR_RANGES_8-VAL
          LIDAR_RANGES_8
          LIDAR_RANGES_9-VAL
          LIDAR_RANGES_9
          LIDAR_RANGES_10-VAL
          LIDAR_RANGES_10
          LIDAR_RANGES_11-VAL
          LIDAR_RANGES_11
          LIDAR_RANGES_12-VAL
          LIDAR_RANGES_12
          LIDAR_RANGES_13-VAL
          LIDAR_RANGES_13
          LIDAR_RANGES_14-VAL
          LIDAR_RANGES_14
          LIDAR_RANGES_15-VAL
          LIDAR_RANGES_15
          LIDAR_RANGES_16-VAL
          LIDAR_RANGES_16
          LIDAR_RANGES_17-VAL
          LIDAR_RANGES_17
          LIDAR_RANGES_18-VAL
          LIDAR_RANGES_18
          LIDAR_RANGES_19-VAL
          LIDAR_RANGES_19
          LIDAR_RANGES_20-VAL
          LIDAR_RANGES_20
          LIDAR_RANGES_21-VAL
          LIDAR_RANGES_21
          LIDAR_RANGES_22-VAL
          LIDAR_RANGES_22
          LIDAR_RANGES_23-VAL
          LIDAR_RANGES_23
          LIDAR_RANGES_24-VAL
          LIDAR_RANGES_24
))