(cl:in-package hehe-msg)
(cl:export '(NUMBER-VAL
          NUMBER
          THROTTLE-VAL
          THROTTLE
          RPM-VAL
          RPM
          SPEED-VAL
          SPEED
          ENGINE_LOAD-VAL
          ENGINE_LOAD
          TEMPERATURE-VAL
          TEMPERATURE
          HUMIDITY-VAL
          HUMIDITY
          ENGINE_STATUS-VAL
          ENGINE_STATUS
          BATTERY_STATUS-VAL
          BATTERY_STATUS
          BATTERY_CAP-VAL
          BATTERY_CAP
          AIR_PRESSURE-VAL
          AIR_PRESSURE
          AIR_TEMPERATURE-VAL
          AIR_TEMPERATURE
          TORQUE-VAL
          TORQUE
          LOAD-VAL
          LOAD
          EFFICIENCY-VAL
          EFFICIENCY
          VOLTAGE-VAL
          VOLTAGE
          CURRENT-VAL
          CURRENT
          DISCHARGE-VAL
          DISCHARGE
          HOURS-VAL
          HOURS
          MINUTES-VAL
          MINUTES
          SECOND-VAL
          SECOND
          HEALTH-VAL
          HEALTH
))