/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QLabel *label;
    QLabel *speed;
    QLabel *rpm;
    QLabel *rpm_text;
    QLabel *speed_text;
    QLabel *speed_1;
    QLabel *throttle;
    QLabel *speed_2;
    QLabel *speed_5;
    QLabel *speed_7;
    QLabel *speed_3;
    QLabel *speed_6;
    QLabel *speed_4;
    QLabel *throttle_text;
    QLabel *temperature;
    QLabel *humidity;
    QLabel *engine_load;
    QLabel *engine_load_text;
    QWidget *page_2;
    QLabel *label_2;
    QLabel *rgb_camera;
    QLabel *ir_camera;
    QLabel *lidar_1;
    QLabel *lidar_2;
    QLabel *lidar_3;
    QLabel *lidar_4;
    QLabel *lidar_5;
    QLabel *lidar_6;
    QLabel *lidar_7;
    QLabel *lidar_8;
    QLabel *lidar_9;
    QLabel *lidar_10;
    QLabel *lidar_11;
    QLabel *lidar_12;
    QLabel *lidar_13;
    QLabel *lidar_14;
    QLabel *lidar_15;
    QLabel *lidar_16;
    QLabel *lidar_17;
    QLabel *lidar_18;
    QLabel *lidar_19;
    QLabel *lidar_20;
    QLabel *lidar_21;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *time_inc;
    QLabel *scan_time;
    QLabel *range_min;
    QLabel *range_max;
    QLabel *range_size;
    QLabel *count;
    QLabel *not_count;
    QLabel *lidar_22;
    QLabel *label_5;
    QLabel *label_16;
    QWidget *page_3;
    QWidget *widget;
    QWidget *page_4;
    QLabel *label_4;
    QLabel *engine_load_txt;
    QLabel *engine_load_val;
    QLabel *throttle_txt;
    QLabel *throttle_val;
    QLabel *air_temp_txt;
    QLabel *air_temp;
    QLabel *air_press_txt;
    QLabel *air_press;
    QLabel *air_temp_txt_2;
    QLabel *air_press_txt_2;
    QWidget *page_5;
    QLabel *label_15;
    QLabel *motor_torq_txt;
    QLabel *current_txt;
    QLabel *voltage_txt;
    QLabel *efficiency_txt;
    QLabel *temperature_txt;
    QLabel *load_txt;
    QLabel *temp_val;
    QLabel *volt_val;
    QLabel *current_val;
    QLabel *torque;
    QLabel *efficiency;
    QLabel *load;
    QLabel *motor_torq_txt_2;
    QLabel *motor_torq_txt_3;
    QLabel *load_txt_2;
    QWidget *page_6;
    QLabel *label_6;
    QLabel *disc_current_txt;
    QLabel *health_txt;
    QLabel *label_21;
    QLabel *label_23;
    QLabel *duration;
    QLabel *health;
    QLabel *disc_current;
    QLabel *voltage_text;
    QLabel *voltage;
    QLabel *label_3;
    QLabel *batt_1;
    QLabel *batt_2;
    QLabel *batt_3;
    QLabel *batt_4;
    QLabel *batt_5;
    QLabel *batt_6;
    QLabel *batt_7;
    QLabel *batt_8;
    QLabel *batt_9;
    QLabel *batt_cap;
    QWidget *page_7;
    QLabel *label_7;
    QListWidget *listWidget;
    QPushButton *shuffle;
    QPushButton *mute;
    QPushButton *back;
    QPushButton *play;
    QPushButton *forward;
    QPushButton *repeat;
    QPushButton *save;
    QPushButton *remove;
    QPushButton *add;
    QSlider *volumeBar;
    QSlider *seekBar;
    QLabel *currentSong;
    QLineEdit *searchBar;
    QLabel *audio;
    QPushButton *main_window;
    QPushButton *lidar_window;
    QPushButton *map_window;
    QPushButton *battery_window;
    QLabel *sub_main;
    QPushButton *music_window;
    QPushButton *Engine_window;
    QLabel *date;
    QLabel *clock;
    QLabel *sub_engine_status;
    QLabel *sub_battery_capacity;
    QPushButton *Electrical_window;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1920, 1080);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        QFont font;
        font.setFamily(QStringLiteral("Bitstream Charter"));
        centralWidget->setFont(font);
        stackedWidget = new QStackedWidget(centralWidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(350, 0, 1500, 720));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        label = new QLabel(page);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(-10, -10, 1500, 720));
        label->setPixmap(QPixmap(QString::fromUtf8("../panel_1.png")));
        label->setScaledContents(true);
        speed = new QLabel(page);
        speed->setObjectName(QStringLiteral("speed"));
        speed->setGeometry(QRect(60, 100, 291, 141));
        QFont font1;
        font1.setFamily(QStringLiteral("Bitstream Vera Sans"));
        font1.setPointSize(115);
        speed->setFont(font1);
        rpm = new QLabel(page);
        rpm->setObjectName(QStringLiteral("rpm"));
        rpm->setGeometry(QRect(1150, 150, 301, 191));
        QFont font2;
        font2.setFamily(QStringLiteral("Bitstream Vera Sans"));
        font2.setPointSize(80);
        rpm->setFont(font2);
        rpm_text = new QLabel(page);
        rpm_text->setObjectName(QStringLiteral("rpm_text"));
        rpm_text->setGeometry(QRect(1170, 80, 211, 91));
        QFont font3;
        font3.setFamily(QStringLiteral("Bitstream Vera Sans"));
        font3.setPointSize(70);
        rpm_text->setFont(font3);
        speed_text = new QLabel(page);
        speed_text->setObjectName(QStringLiteral("speed_text"));
        speed_text->setGeometry(QRect(110, 220, 221, 91));
        QFont font4;
        font4.setFamily(QStringLiteral("Bitstream Vera Sans"));
        font4.setPointSize(50);
        font4.setBold(true);
        font4.setWeight(75);
        speed_text->setFont(font4);
        speed_1 = new QLabel(page);
        speed_1->setObjectName(QStringLiteral("speed_1"));
        speed_1->setGeometry(QRect(350, 270, 90, 25));
        speed_1->setPixmap(QPixmap(QString::fromUtf8("../ver_1/hijau.jpg")));
        throttle = new QLabel(page);
        throttle->setObjectName(QStringLiteral("throttle"));
        throttle->setGeometry(QRect(630, 150, 371, 151));
        QFont font5;
        font5.setFamily(QStringLiteral("Bitstream Vera Sans"));
        font5.setPointSize(120);
        throttle->setFont(font5);
        speed_2 = new QLabel(page);
        speed_2->setObjectName(QStringLiteral("speed_2"));
        speed_2->setGeometry(QRect(350, 240, 90, 25));
        speed_2->setPixmap(QPixmap(QString::fromUtf8("../ver_1/hijau muda.png")));
        speed_5 = new QLabel(page);
        speed_5->setObjectName(QStringLiteral("speed_5"));
        speed_5->setGeometry(QRect(350, 150, 90, 25));
        speed_5->setPixmap(QPixmap(QString::fromUtf8("../ver_1/orange.png")));
        speed_7 = new QLabel(page);
        speed_7->setObjectName(QStringLiteral("speed_7"));
        speed_7->setGeometry(QRect(350, 90, 90, 25));
        speed_7->setPixmap(QPixmap(QString::fromUtf8("../ver_1/merahmuda.jpg")));
        speed_3 = new QLabel(page);
        speed_3->setObjectName(QStringLiteral("speed_3"));
        speed_3->setGeometry(QRect(350, 210, 90, 25));
        speed_3->setPixmap(QPixmap(QString::fromUtf8("../ver_1/kuning.jpg")));
        speed_6 = new QLabel(page);
        speed_6->setObjectName(QStringLiteral("speed_6"));
        speed_6->setGeometry(QRect(350, 120, 90, 25));
        speed_6->setPixmap(QPixmap(QString::fromUtf8("../ver_1/orange muda.png")));
        speed_4 = new QLabel(page);
        speed_4->setObjectName(QStringLiteral("speed_4"));
        speed_4->setGeometry(QRect(350, 180, 90, 25));
        speed_4->setPixmap(QPixmap(QString::fromUtf8("../ver_1/kuning muda.png")));
        throttle_text = new QLabel(page);
        throttle_text->setObjectName(QStringLiteral("throttle_text"));
        throttle_text->setGeometry(QRect(640, 80, 361, 91));
        QFont font6;
        font6.setFamily(QStringLiteral("Bitstream Vera Sans"));
        font6.setPointSize(50);
        throttle_text->setFont(font6);
        temperature = new QLabel(page);
        temperature->setObjectName(QStringLiteral("temperature"));
        temperature->setGeometry(QRect(110, 490, 191, 141));
        QFont font7;
        font7.setFamily(QStringLiteral("Bitstream Vera Sans"));
        font7.setPointSize(60);
        temperature->setFont(font7);
        humidity = new QLabel(page);
        humidity->setObjectName(QStringLiteral("humidity"));
        humidity->setGeometry(QRect(570, 510, 181, 131));
        humidity->setFont(font7);
        engine_load = new QLabel(page);
        engine_load->setObjectName(QStringLiteral("engine_load"));
        engine_load->setGeometry(QRect(950, 530, 381, 101));
        QFont font8;
        font8.setFamily(QStringLiteral("Bitstream Vera Sans"));
        font8.setPointSize(65);
        engine_load->setFont(font8);
        engine_load_text = new QLabel(page);
        engine_load_text->setObjectName(QStringLiteral("engine_load_text"));
        engine_load_text->setGeometry(QRect(920, 450, 361, 91));
        QFont font9;
        font9.setFamily(QStringLiteral("Bitstream Vera Sans"));
        font9.setPointSize(40);
        engine_load_text->setFont(font9);
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        label_2 = new QLabel(page_2);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(0, 0, 1500, 720));
        label_2->setPixmap(QPixmap(QString::fromUtf8("../panel_2.png")));
        label_2->setScaledContents(true);
        rgb_camera = new QLabel(page_2);
        rgb_camera->setObjectName(QStringLiteral("rgb_camera"));
        rgb_camera->setGeometry(QRect(1060, 400, 421, 281));
        rgb_camera->setPixmap(QPixmap(QString::fromUtf8("../1.png")));
        rgb_camera->setScaledContents(true);
        ir_camera = new QLabel(page_2);
        ir_camera->setObjectName(QStringLiteral("ir_camera"));
        ir_camera->setGeometry(QRect(1057, 30, 421, 281));
        ir_camera->setPixmap(QPixmap(QString::fromUtf8("../4.png")));
        ir_camera->setScaledContents(true);
        lidar_1 = new QLabel(page_2);
        lidar_1->setObjectName(QStringLiteral("lidar_1"));
        lidar_1->setGeometry(QRect(670, 35, 60, 41));
        lidar_1->setPixmap(QPixmap(QString::fromUtf8("../b-removebg-preview.png")));
        lidar_1->setScaledContents(true);
        lidar_2 = new QLabel(page_2);
        lidar_2->setObjectName(QStringLiteral("lidar_2"));
        lidar_2->setGeometry(QRect(757, 42, 61, 41));
        lidar_2->setPixmap(QPixmap(QString::fromUtf8("../b-removebg-preview.png")));
        lidar_2->setScaledContents(true);
        lidar_3 = new QLabel(page_2);
        lidar_3->setObjectName(QStringLiteral("lidar_3"));
        lidar_3->setGeometry(QRect(840, 80, 60, 41));
        lidar_3->setPixmap(QPixmap(QString::fromUtf8("../b-removebg-preview.png")));
        lidar_3->setScaledContents(true);
        lidar_4 = new QLabel(page_2);
        lidar_4->setObjectName(QStringLiteral("lidar_4"));
        lidar_4->setGeometry(QRect(905, 140, 60, 41));
        lidar_4->setPixmap(QPixmap(QString::fromUtf8("../b-removebg-preview.png")));
        lidar_4->setScaledContents(true);
        lidar_5 = new QLabel(page_2);
        lidar_5->setObjectName(QStringLiteral("lidar_5"));
        lidar_5->setGeometry(QRect(950, 220, 60, 41));
        lidar_5->setPixmap(QPixmap(QString::fromUtf8("../b-removebg-preview.png")));
        lidar_5->setScaledContents(true);
        lidar_6 = new QLabel(page_2);
        lidar_6->setObjectName(QStringLiteral("lidar_6"));
        lidar_6->setGeometry(QRect(970, 320, 60, 41));
        lidar_6->setPixmap(QPixmap(QString::fromUtf8("../b-removebg-preview.png")));
        lidar_6->setScaledContents(true);
        lidar_7 = new QLabel(page_2);
        lidar_7->setObjectName(QStringLiteral("lidar_7"));
        lidar_7->setGeometry(QRect(978, 420, 60, 41));
        lidar_7->setPixmap(QPixmap(QString::fromUtf8("../b-removebg-preview.png")));
        lidar_7->setScaledContents(true);
        lidar_8 = new QLabel(page_2);
        lidar_8->setObjectName(QStringLiteral("lidar_8"));
        lidar_8->setGeometry(QRect(960, 510, 41, 41));
        lidar_8->setPixmap(QPixmap(QString::fromUtf8("../red-circle-red-point-transparent-background-11563241690fqswnj7pqe-removebg-preview.png")));
        lidar_8->setScaledContents(true);
        lidar_9 = new QLabel(page_2);
        lidar_9->setObjectName(QStringLiteral("lidar_9"));
        lidar_9->setGeometry(QRect(920, 570, 41, 41));
        lidar_9->setPixmap(QPixmap(QString::fromUtf8("../red-circle-red-point-transparent-background-11563241690fqswnj7pqe-removebg-preview.png")));
        lidar_9->setScaledContents(true);
        lidar_10 = new QLabel(page_2);
        lidar_10->setObjectName(QStringLiteral("lidar_10"));
        lidar_10->setGeometry(QRect(850, 620, 41, 41));
        lidar_10->setPixmap(QPixmap(QString::fromUtf8("../red-circle-red-point-transparent-background-11563241690fqswnj7pqe-removebg-preview.png")));
        lidar_10->setScaledContents(true);
        lidar_11 = new QLabel(page_2);
        lidar_11->setObjectName(QStringLiteral("lidar_11"));
        lidar_11->setGeometry(QRect(770, 650, 41, 41));
        lidar_11->setPixmap(QPixmap(QString::fromUtf8("../red-circle-red-point-transparent-background-11563241690fqswnj7pqe-removebg-preview.png")));
        lidar_11->setScaledContents(true);
        lidar_12 = new QLabel(page_2);
        lidar_12->setObjectName(QStringLiteral("lidar_12"));
        lidar_12->setGeometry(QRect(680, 660, 41, 41));
        lidar_12->setPixmap(QPixmap(QString::fromUtf8("../red-circle-red-point-transparent-background-11563241690fqswnj7pqe-removebg-preview.png")));
        lidar_12->setScaledContents(true);
        lidar_13 = new QLabel(page_2);
        lidar_13->setObjectName(QStringLiteral("lidar_13"));
        lidar_13->setGeometry(QRect(600, 640, 41, 41));
        lidar_13->setPixmap(QPixmap(QString::fromUtf8("../red-circle-red-point-transparent-background-11563241690fqswnj7pqe-removebg-preview.png")));
        lidar_13->setScaledContents(true);
        lidar_14 = new QLabel(page_2);
        lidar_14->setObjectName(QStringLiteral("lidar_14"));
        lidar_14->setGeometry(QRect(530, 590, 41, 41));
        lidar_14->setPixmap(QPixmap(QString::fromUtf8("../red-circle-red-point-transparent-background-11563241690fqswnj7pqe-removebg-preview.png")));
        lidar_14->setScaledContents(true);
        lidar_15 = new QLabel(page_2);
        lidar_15->setObjectName(QStringLiteral("lidar_15"));
        lidar_15->setGeometry(QRect(460, 510, 41, 41));
        lidar_15->setPixmap(QPixmap(QString::fromUtf8("../red-circle-red-point-transparent-background-11563241690fqswnj7pqe-removebg-preview.png")));
        lidar_15->setScaledContents(true);
        lidar_16 = new QLabel(page_2);
        lidar_16->setObjectName(QStringLiteral("lidar_16"));
        lidar_16->setGeometry(QRect(420, 420, 60, 41));
        lidar_16->setPixmap(QPixmap(QString::fromUtf8("../b-removebg-preview.png")));
        lidar_16->setScaledContents(true);
        lidar_17 = new QLabel(page_2);
        lidar_17->setObjectName(QStringLiteral("lidar_17"));
        lidar_17->setGeometry(QRect(410, 310, 60, 41));
        lidar_17->setPixmap(QPixmap(QString::fromUtf8("../b-removebg-preview.png")));
        lidar_17->setScaledContents(true);
        lidar_18 = new QLabel(page_2);
        lidar_18->setObjectName(QStringLiteral("lidar_18"));
        lidar_18->setGeometry(QRect(430, 230, 60, 41));
        lidar_18->setPixmap(QPixmap(QString::fromUtf8("../b-removebg-preview.png")));
        lidar_18->setScaledContents(true);
        lidar_19 = new QLabel(page_2);
        lidar_19->setObjectName(QStringLiteral("lidar_19"));
        lidar_19->setGeometry(QRect(470, 160, 60, 41));
        lidar_19->setPixmap(QPixmap(QString::fromUtf8("../b-removebg-preview.png")));
        lidar_19->setScaledContents(true);
        lidar_20 = new QLabel(page_2);
        lidar_20->setObjectName(QStringLiteral("lidar_20"));
        lidar_20->setGeometry(QRect(520, 100, 60, 41));
        lidar_20->setPixmap(QPixmap(QString::fromUtf8("../b-removebg-preview.png")));
        lidar_20->setScaledContents(true);
        lidar_21 = new QLabel(page_2);
        lidar_21->setObjectName(QStringLiteral("lidar_21"));
        lidar_21->setGeometry(QRect(600, 60, 60, 41));
        lidar_21->setPixmap(QPixmap(QString::fromUtf8("../b-removebg-preview.png")));
        lidar_21->setScaledContents(true);
        label_8 = new QLabel(page_2);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(50, 120, 211, 31));
        QFont font10;
        font10.setPointSize(20);
        label_8->setFont(font10);
        label_9 = new QLabel(page_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(50, 170, 191, 31));
        label_9->setFont(font10);
        label_10 = new QLabel(page_2);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(50, 220, 161, 31));
        label_10->setFont(font10);
        label_11 = new QLabel(page_2);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(50, 270, 191, 41));
        label_11->setFont(font10);
        label_12 = new QLabel(page_2);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(50, 440, 171, 41));
        label_12->setFont(font10);
        label_13 = new QLabel(page_2);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(50, 570, 151, 31));
        label_13->setFont(font10);
        label_14 = new QLabel(page_2);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(50, 510, 131, 31));
        label_14->setFont(font10);
        time_inc = new QLabel(page_2);
        time_inc->setObjectName(QStringLiteral("time_inc"));
        time_inc->setGeometry(QRect(210, 120, 171, 41));
        time_inc->setFont(font10);
        scan_time = new QLabel(page_2);
        scan_time->setObjectName(QStringLiteral("scan_time"));
        scan_time->setGeometry(QRect(210, 170, 171, 41));
        scan_time->setFont(font10);
        range_min = new QLabel(page_2);
        range_min->setObjectName(QStringLiteral("range_min"));
        range_min->setGeometry(QRect(210, 220, 181, 41));
        range_min->setFont(font10);
        range_max = new QLabel(page_2);
        range_max->setObjectName(QStringLiteral("range_max"));
        range_max->setGeometry(QRect(210, 270, 181, 41));
        range_max->setFont(font10);
        range_size = new QLabel(page_2);
        range_size->setObjectName(QStringLiteral("range_size"));
        range_size->setGeometry(QRect(240, 440, 51, 41));
        range_size->setFont(font10);
        count = new QLabel(page_2);
        count->setObjectName(QStringLiteral("count"));
        count->setGeometry(QRect(240, 505, 51, 41));
        count->setFont(font10);
        not_count = new QLabel(page_2);
        not_count->setObjectName(QStringLiteral("not_count"));
        not_count->setGeometry(QRect(240, 565, 51, 41));
        not_count->setFont(font10);
        lidar_22 = new QLabel(page_2);
        lidar_22->setObjectName(QStringLiteral("lidar_22"));
        lidar_22->setGeometry(QRect(690, 460, 41, 41));
        lidar_22->setPixmap(QPixmap(QString::fromUtf8("../hijau.jpg")));
        lidar_22->setScaledContents(true);
        label_5 = new QLabel(page_2);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(420, 450, 301, 71));
        label_5->setPixmap(QPixmap(QString::fromUtf8("../line-removebg-preview.png")));
        label_5->setScaledContents(true);
        label_16 = new QLabel(page_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(700, 450, 321, 61));
        label_16->setPixmap(QPixmap(QString::fromUtf8("../line-b.png")));
        label_16->setScaledContents(true);
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        widget = new QWidget(page_3);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(0, 0, 1500, 720));
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        label_4 = new QLabel(page_4);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(0, 0, 1500, 720));
        label_4->setPixmap(QPixmap(QString::fromUtf8("../panel_10.png")));
        label_4->setScaledContents(true);
        engine_load_txt = new QLabel(page_4);
        engine_load_txt->setObjectName(QStringLiteral("engine_load_txt"));
        engine_load_txt->setGeometry(QRect(860, 60, 231, 81));
        QFont font11;
        font11.setPointSize(50);
        engine_load_txt->setFont(font11);
        engine_load_val = new QLabel(page_4);
        engine_load_val->setObjectName(QStringLiteral("engine_load_val"));
        engine_load_val->setGeometry(QRect(840, 140, 321, 121));
        QFont font12;
        font12.setPointSize(60);
        engine_load_val->setFont(font12);
        throttle_txt = new QLabel(page_4);
        throttle_txt->setObjectName(QStringLiteral("throttle_txt"));
        throttle_txt->setGeometry(QRect(1220, 70, 241, 50));
        throttle_txt->setFont(font11);
        throttle_val = new QLabel(page_4);
        throttle_val->setObjectName(QStringLiteral("throttle_val"));
        throttle_val->setGeometry(QRect(1210, 150, 261, 101));
        QFont font13;
        font13.setPointSize(100);
        throttle_val->setFont(font13);
        air_temp_txt = new QLabel(page_4);
        air_temp_txt->setObjectName(QStringLiteral("air_temp_txt"));
        air_temp_txt->setGeometry(QRect(840, 390, 500, 50));
        QFont font14;
        font14.setPointSize(30);
        air_temp_txt->setFont(font14);
        air_temp = new QLabel(page_4);
        air_temp->setObjectName(QStringLiteral("air_temp"));
        air_temp->setGeometry(QRect(860, 510, 231, 101));
        air_temp->setFont(font13);
        air_press_txt = new QLabel(page_4);
        air_press_txt->setObjectName(QStringLiteral("air_press_txt"));
        air_press_txt->setGeometry(QRect(1200, 390, 321, 50));
        air_press_txt->setFont(font14);
        air_press = new QLabel(page_4);
        air_press->setObjectName(QStringLiteral("air_press"));
        air_press->setGeometry(QRect(1200, 500, 271, 121));
        QFont font15;
        font15.setPointSize(70);
        air_press->setFont(font15);
        air_temp_txt_2 = new QLabel(page_4);
        air_temp_txt_2->setObjectName(QStringLiteral("air_temp_txt_2"));
        air_temp_txt_2->setGeometry(QRect(840, 440, 251, 50));
        air_temp_txt_2->setFont(font14);
        air_press_txt_2 = new QLabel(page_4);
        air_press_txt_2->setObjectName(QStringLiteral("air_press_txt_2"));
        air_press_txt_2->setGeometry(QRect(1200, 440, 321, 50));
        air_press_txt_2->setFont(font14);
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName(QStringLiteral("page_5"));
        label_15 = new QLabel(page_5);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(0, 0, 1500, 720));
        label_15->setPixmap(QPixmap(QString::fromUtf8("../panel_9.png")));
        label_15->setScaledContents(true);
        motor_torq_txt = new QLabel(page_5);
        motor_torq_txt->setObjectName(QStringLiteral("motor_torq_txt"));
        motor_torq_txt->setGeometry(QRect(1110, 90, 251, 131));
        motor_torq_txt->setFont(font11);
        current_txt = new QLabel(page_5);
        current_txt->setObjectName(QStringLiteral("current_txt"));
        current_txt->setGeometry(QRect(790, 40, 141, 61));
        current_txt->setFont(font14);
        voltage_txt = new QLabel(page_5);
        voltage_txt->setObjectName(QStringLiteral("voltage_txt"));
        voltage_txt->setGeometry(QRect(460, 40, 151, 51));
        voltage_txt->setFont(font14);
        efficiency_txt = new QLabel(page_5);
        efficiency_txt->setObjectName(QStringLiteral("efficiency_txt"));
        efficiency_txt->setGeometry(QRect(630, 300, 191, 51));
        efficiency_txt->setFont(font14);
        temperature_txt = new QLabel(page_5);
        temperature_txt->setObjectName(QStringLiteral("temperature_txt"));
        temperature_txt->setGeometry(QRect(90, 30, 231, 51));
        temperature_txt->setFont(font14);
        load_txt = new QLabel(page_5);
        load_txt->setObjectName(QStringLiteral("load_txt"));
        load_txt->setGeometry(QRect(250, 290, 91, 41));
        load_txt->setFont(font14);
        temp_val = new QLabel(page_5);
        temp_val->setObjectName(QStringLiteral("temp_val"));
        temp_val->setGeometry(QRect(100, 80, 221, 121));
        temp_val->setFont(font13);
        volt_val = new QLabel(page_5);
        volt_val->setObjectName(QStringLiteral("volt_val"));
        volt_val->setGeometry(QRect(440, 80, 181, 121));
        QFont font16;
        font16.setPointSize(80);
        volt_val->setFont(font16);
        current_val = new QLabel(page_5);
        current_val->setObjectName(QStringLiteral("current_val"));
        current_val->setGeometry(QRect(760, 80, 191, 121));
        current_val->setFont(font16);
        torque = new QLabel(page_5);
        torque->setObjectName(QStringLiteral("torque"));
        torque->setGeometry(QRect(1100, 270, 241, 121));
        torque->setFont(font13);
        efficiency = new QLabel(page_5);
        efficiency->setObjectName(QStringLiteral("efficiency"));
        efficiency->setGeometry(QRect(590, 360, 271, 121));
        efficiency->setFont(font13);
        load = new QLabel(page_5);
        load->setObjectName(QStringLiteral("load"));
        load->setGeometry(QRect(220, 320, 131, 121));
        load->setFont(font12);
        motor_torq_txt_2 = new QLabel(page_5);
        motor_torq_txt_2->setObjectName(QStringLiteral("motor_torq_txt_2"));
        motor_torq_txt_2->setGeometry(QRect(1090, 150, 251, 131));
        motor_torq_txt_2->setFont(font11);
        motor_torq_txt_3 = new QLabel(page_5);
        motor_torq_txt_3->setObjectName(QStringLiteral("motor_torq_txt_3"));
        motor_torq_txt_3->setGeometry(QRect(1140, 430, 151, 131));
        motor_torq_txt_3->setFont(font15);
        load_txt_2 = new QLabel(page_5);
        load_txt_2->setObjectName(QStringLiteral("load_txt_2"));
        load_txt_2->setGeometry(QRect(260, 420, 51, 51));
        load_txt_2->setFont(font14);
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName(QStringLiteral("page_6"));
        label_6 = new QLabel(page_6);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(30, 0, 1491, 720));
        label_6->setPixmap(QPixmap(QString::fromUtf8("../panel_8.png")));
        label_6->setScaledContents(true);
        disc_current_txt = new QLabel(page_6);
        disc_current_txt->setObjectName(QStringLiteral("disc_current_txt"));
        disc_current_txt->setGeometry(QRect(840, 450, 541, 111));
        disc_current_txt->setFont(font11);
        health_txt = new QLabel(page_6);
        health_txt->setObjectName(QStringLiteral("health_txt"));
        health_txt->setGeometry(QRect(180, 140, 91, 51));
        health_txt->setFont(font10);
        label_21 = new QLabel(page_6);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(690, 190, 181, 61));
        label_21->setPixmap(QPixmap(QString::fromUtf8("../index.jpeg")));
        label_23 = new QLabel(page_6);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(660, 330, 221, 31));
        label_23->setPixmap(QPixmap(QString::fromUtf8("../index.jpeg")));
        duration = new QLabel(page_6);
        duration->setObjectName(QStringLiteral("duration"));
        duration->setGeometry(QRect(700, 315, 181, 61));
        duration->setFont(font10);
        duration->setPixmap(QPixmap(QString::fromUtf8("../index.jpeg")));
        health = new QLabel(page_6);
        health->setObjectName(QStringLiteral("health"));
        health->setGeometry(QRect(150, 200, 181, 61));
        QFont font17;
        font17.setPointSize(40);
        health->setFont(font17);
        disc_current = new QLabel(page_6);
        disc_current->setObjectName(QStringLiteral("disc_current"));
        disc_current->setGeometry(QRect(1090, 580, 171, 71));
        disc_current->setFont(font11);
        voltage_text = new QLabel(page_6);
        voltage_text->setObjectName(QStringLiteral("voltage_text"));
        voltage_text->setGeometry(QRect(180, 450, 341, 101));
        voltage_text->setFont(font11);
        voltage = new QLabel(page_6);
        voltage->setObjectName(QStringLiteral("voltage"));
        voltage->setGeometry(QRect(220, 590, 181, 71));
        voltage->setFont(font11);
        label_3 = new QLabel(page_6);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(600, 130, 371, 191));
        label_3->setPixmap(QPixmap(QString::fromUtf8("../index.jpeg")));
        label_3->setScaledContents(true);
        batt_1 = new QLabel(page_6);
        batt_1->setObjectName(QStringLiteral("batt_1"));
        batt_1->setGeometry(QRect(600, 130, 31, 191));
        batt_1->setPixmap(QPixmap(QString::fromUtf8("../merahmuda.jpg")));
        batt_1->setScaledContents(true);
        batt_2 = new QLabel(page_6);
        batt_2->setObjectName(QStringLiteral("batt_2"));
        batt_2->setGeometry(QRect(640, 130, 31, 191));
        batt_2->setPixmap(QPixmap(QString::fromUtf8("../merahmuda.jpg")));
        batt_2->setScaledContents(true);
        batt_3 = new QLabel(page_6);
        batt_3->setObjectName(QStringLiteral("batt_3"));
        batt_3->setGeometry(QRect(680, 130, 31, 191));
        batt_3->setPixmap(QPixmap(QString::fromUtf8("../merahmuda.jpg")));
        batt_3->setScaledContents(true);
        batt_4 = new QLabel(page_6);
        batt_4->setObjectName(QStringLiteral("batt_4"));
        batt_4->setGeometry(QRect(720, 130, 31, 191));
        batt_4->setPixmap(QPixmap(QString::fromUtf8("../merahmuda.jpg")));
        batt_4->setScaledContents(true);
        batt_5 = new QLabel(page_6);
        batt_5->setObjectName(QStringLiteral("batt_5"));
        batt_5->setGeometry(QRect(760, 130, 31, 191));
        batt_5->setPixmap(QPixmap(QString::fromUtf8("../merahmuda.jpg")));
        batt_5->setScaledContents(true);
        batt_6 = new QLabel(page_6);
        batt_6->setObjectName(QStringLiteral("batt_6"));
        batt_6->setGeometry(QRect(800, 130, 31, 191));
        batt_6->setPixmap(QPixmap(QString::fromUtf8("../merahmuda.jpg")));
        batt_6->setScaledContents(true);
        batt_7 = new QLabel(page_6);
        batt_7->setObjectName(QStringLiteral("batt_7"));
        batt_7->setGeometry(QRect(840, 130, 31, 191));
        batt_7->setPixmap(QPixmap(QString::fromUtf8("../merahmuda.jpg")));
        batt_7->setScaledContents(true);
        batt_8 = new QLabel(page_6);
        batt_8->setObjectName(QStringLiteral("batt_8"));
        batt_8->setGeometry(QRect(880, 130, 31, 191));
        batt_8->setPixmap(QPixmap(QString::fromUtf8("../merahmuda.jpg")));
        batt_8->setScaledContents(true);
        batt_9 = new QLabel(page_6);
        batt_9->setObjectName(QStringLiteral("batt_9"));
        batt_9->setGeometry(QRect(920, 130, 31, 191));
        batt_9->setPixmap(QPixmap(QString::fromUtf8("../merahmuda.jpg")));
        batt_9->setScaledContents(true);
        batt_cap = new QLabel(page_6);
        batt_cap->setObjectName(QStringLiteral("batt_cap"));
        batt_cap->setGeometry(QRect(690, 190, 181, 61));
        batt_cap->setFont(font11);
        batt_cap->setPixmap(QPixmap(QString::fromUtf8("../index.jpeg")));
        stackedWidget->addWidget(page_6);
        page_7 = new QWidget();
        page_7->setObjectName(QStringLiteral("page_7"));
        label_7 = new QLabel(page_7);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(0, 0, 1500, 720));
        label_7->setPixmap(QPixmap(QString::fromUtf8("../panel_6.png")));
        listWidget = new QListWidget(page_7);
        listWidget->setObjectName(QStringLiteral("listWidget"));
        listWidget->setGeometry(QRect(880, 140, 491, 351));
        shuffle = new QPushButton(page_7);
        shuffle->setObjectName(QStringLiteral("shuffle"));
        shuffle->setGeometry(QRect(280, 520, 91, 51));
        mute = new QPushButton(page_7);
        mute->setObjectName(QStringLiteral("mute"));
        mute->setGeometry(QRect(180, 520, 91, 51));
        back = new QPushButton(page_7);
        back->setObjectName(QStringLiteral("back"));
        back->setGeometry(QRect(680, 520, 91, 51));
        play = new QPushButton(page_7);
        play->setObjectName(QStringLiteral("play"));
        play->setGeometry(QRect(780, 520, 91, 51));
        forward = new QPushButton(page_7);
        forward->setObjectName(QStringLiteral("forward"));
        forward->setGeometry(QRect(880, 520, 91, 51));
        repeat = new QPushButton(page_7);
        repeat->setObjectName(QStringLiteral("repeat"));
        repeat->setGeometry(QRect(980, 520, 91, 51));
        save = new QPushButton(page_7);
        save->setObjectName(QStringLiteral("save"));
        save->setGeometry(QRect(1080, 520, 91, 51));
        remove = new QPushButton(page_7);
        remove->setObjectName(QStringLiteral("remove"));
        remove->setGeometry(QRect(1180, 520, 91, 51));
        add = new QPushButton(page_7);
        add->setObjectName(QStringLiteral("add"));
        add->setGeometry(QRect(1280, 520, 91, 51));
        volumeBar = new QSlider(page_7);
        volumeBar->setObjectName(QStringLiteral("volumeBar"));
        volumeBar->setGeometry(QRect(420, 540, 160, 16));
        volumeBar->setOrientation(Qt::Horizontal);
        seekBar = new QSlider(page_7);
        seekBar->setObjectName(QStringLiteral("seekBar"));
        seekBar->setGeometry(QRect(180, 500, 1191, 16));
        seekBar->setOrientation(Qt::Horizontal);
        currentSong = new QLabel(page_7);
        currentSong->setObjectName(QStringLiteral("currentSong"));
        currentSong->setGeometry(QRect(190, 440, 811, 51));
        currentSong->setFont(font14);
        searchBar = new QLineEdit(page_7);
        searchBar->setObjectName(QStringLiteral("searchBar"));
        searchBar->setGeometry(QRect(410, 40, 731, 51));
        audio = new QLabel(page_7);
        audio->setObjectName(QStringLiteral("audio"));
        audio->setGeometry(QRect(180, 140, 561, 291));
        audio->setPixmap(QPixmap(QString::fromUtf8("../audio.gif")));
        audio->setScaledContents(true);
        stackedWidget->addWidget(page_7);
        main_window = new QPushButton(centralWidget);
        main_window->setObjectName(QStringLiteral("main_window"));
        main_window->setGeometry(QRect(0, 0, 300, 100));
        main_window->setFont(font10);
        lidar_window = new QPushButton(centralWidget);
        lidar_window->setObjectName(QStringLiteral("lidar_window"));
        lidar_window->setGeometry(QRect(0, 100, 300, 100));
        lidar_window->setFont(font10);
        map_window = new QPushButton(centralWidget);
        map_window->setObjectName(QStringLiteral("map_window"));
        map_window->setGeometry(QRect(0, 200, 300, 100));
        map_window->setFont(font10);
        battery_window = new QPushButton(centralWidget);
        battery_window->setObjectName(QStringLiteral("battery_window"));
        battery_window->setGeometry(QRect(0, 500, 300, 100));
        battery_window->setFont(font10);
        sub_main = new QLabel(centralWidget);
        sub_main->setObjectName(QStringLiteral("sub_main"));
        sub_main->setGeometry(QRect(0, 760, 1850, 231));
        sub_main->setPixmap(QPixmap(QString::fromUtf8("../panel_7.png")));
        sub_main->setScaledContents(true);
        music_window = new QPushButton(centralWidget);
        music_window->setObjectName(QStringLiteral("music_window"));
        music_window->setGeometry(QRect(0, 600, 300, 100));
        music_window->setFont(font10);
        Engine_window = new QPushButton(centralWidget);
        Engine_window->setObjectName(QStringLiteral("Engine_window"));
        Engine_window->setGeometry(QRect(0, 300, 300, 100));
        Engine_window->setFont(font10);
        date = new QLabel(centralWidget);
        date->setObjectName(QStringLiteral("date"));
        date->setGeometry(QRect(720, 790, 461, 61));
        date->setFont(font14);
        clock = new QLabel(centralWidget);
        clock->setObjectName(QStringLiteral("clock"));
        clock->setGeometry(QRect(720, 850, 431, 101));
        clock->setFont(font15);
        sub_engine_status = new QLabel(centralWidget);
        sub_engine_status->setObjectName(QStringLiteral("sub_engine_status"));
        sub_engine_status->setGeometry(QRect(1530, 790, 201, 51));
        sub_engine_status->setFont(font14);
        sub_battery_capacity = new QLabel(centralWidget);
        sub_battery_capacity->setObjectName(QStringLiteral("sub_battery_capacity"));
        sub_battery_capacity->setGeometry(QRect(1530, 850, 161, 51));
        sub_battery_capacity->setFont(font14);
        Electrical_window = new QPushButton(centralWidget);
        Electrical_window->setObjectName(QStringLiteral("Electrical_window"));
        Electrical_window->setGeometry(QRect(0, 400, 300, 100));
        Electrical_window->setFont(font10);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1920, 22));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        label->setText(QString());
        speed->setText(QApplication::translate("MainWindow", "423", Q_NULLPTR));
        rpm->setText(QApplication::translate("MainWindow", "1024", Q_NULLPTR));
        rpm_text->setText(QApplication::translate("MainWindow", "RPM", Q_NULLPTR));
        speed_text->setText(QApplication::translate("MainWindow", "Km/H", Q_NULLPTR));
        speed_1->setText(QString());
        throttle->setText(QApplication::translate("MainWindow", "42%", Q_NULLPTR));
        speed_2->setText(QString());
        speed_5->setText(QString());
        speed_7->setText(QString());
        speed_3->setText(QString());
        speed_6->setText(QString());
        speed_4->setText(QString());
        throttle_text->setText(QApplication::translate("MainWindow", "THROTTLE", Q_NULLPTR));
        temperature->setText(QApplication::translate("MainWindow", "42c", Q_NULLPTR));
        humidity->setText(QApplication::translate("MainWindow", "42%", Q_NULLPTR));
        engine_load->setText(QApplication::translate("MainWindow", "102%", Q_NULLPTR));
        engine_load_text->setText(QApplication::translate("MainWindow", "Engine Load", Q_NULLPTR));
        label_2->setText(QString());
        rgb_camera->setText(QString());
        ir_camera->setText(QString());
        lidar_1->setText(QString());
        lidar_2->setText(QString());
        lidar_3->setText(QString());
        lidar_4->setText(QString());
        lidar_5->setText(QString());
        lidar_6->setText(QString());
        lidar_7->setText(QString());
        lidar_8->setText(QString());
        lidar_9->setText(QString());
        lidar_10->setText(QString());
        lidar_11->setText(QString());
        lidar_12->setText(QString());
        lidar_13->setText(QString());
        lidar_14->setText(QString());
        lidar_15->setText(QString());
        lidar_16->setText(QString());
        lidar_17->setText(QString());
        lidar_18->setText(QString());
        lidar_19->setText(QString());
        lidar_20->setText(QString());
        lidar_21->setText(QString());
        label_8->setText(QApplication::translate("MainWindow", "Time Inc :", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "Scan Time :", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "Range Min :", Q_NULLPTR));
        label_11->setText(QApplication::translate("MainWindow", "Range Max :", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", "Range Size :", Q_NULLPTR));
        label_13->setText(QApplication::translate("MainWindow", "Not Count :", Q_NULLPTR));
        label_14->setText(QApplication::translate("MainWindow", "Count :", Q_NULLPTR));
        time_inc->setText(QApplication::translate("MainWindow", "100", Q_NULLPTR));
        scan_time->setText(QApplication::translate("MainWindow", "100", Q_NULLPTR));
        range_min->setText(QApplication::translate("MainWindow", "100", Q_NULLPTR));
        range_max->setText(QApplication::translate("MainWindow", "100", Q_NULLPTR));
        range_size->setText(QApplication::translate("MainWindow", "100", Q_NULLPTR));
        count->setText(QApplication::translate("MainWindow", "100", Q_NULLPTR));
        not_count->setText(QApplication::translate("MainWindow", "100", Q_NULLPTR));
        lidar_22->setText(QString());
        label_5->setText(QString());
        label_16->setText(QString());
        label_4->setText(QString());
        engine_load_txt->setText(QApplication::translate("MainWindow", "Engine", Q_NULLPTR));
        engine_load_val->setText(QApplication::translate("MainWindow", "42.32%", Q_NULLPTR));
        throttle_txt->setText(QApplication::translate("MainWindow", "Throttle ", Q_NULLPTR));
        throttle_val->setText(QApplication::translate("MainWindow", "42%", Q_NULLPTR));
        air_temp_txt->setText(QApplication::translate("MainWindow", "Intake", Q_NULLPTR));
        air_temp->setText(QApplication::translate("MainWindow", "42c", Q_NULLPTR));
        air_press_txt->setText(QApplication::translate("MainWindow", "Intake", Q_NULLPTR));
        air_press->setText(QApplication::translate("MainWindow", "42psi", Q_NULLPTR));
        air_temp_txt_2->setText(QApplication::translate("MainWindow", "Temperature", Q_NULLPTR));
        air_press_txt_2->setText(QApplication::translate("MainWindow", "Pressure", Q_NULLPTR));
        label_15->setText(QString());
        motor_torq_txt->setText(QApplication::translate("MainWindow", "Motor", Q_NULLPTR));
        current_txt->setText(QApplication::translate("MainWindow", "Current", Q_NULLPTR));
        voltage_txt->setText(QApplication::translate("MainWindow", "Voltage", Q_NULLPTR));
        efficiency_txt->setText(QApplication::translate("MainWindow", "Efficiency", Q_NULLPTR));
        temperature_txt->setText(QApplication::translate("MainWindow", "Temperature", Q_NULLPTR));
        load_txt->setText(QApplication::translate("MainWindow", "Load", Q_NULLPTR));
        temp_val->setText(QApplication::translate("MainWindow", "42c", Q_NULLPTR));
        volt_val->setText(QApplication::translate("MainWindow", "42v", Q_NULLPTR));
        current_val->setText(QApplication::translate("MainWindow", "42A", Q_NULLPTR));
        torque->setText(QApplication::translate("MainWindow", "423", Q_NULLPTR));
        efficiency->setText(QApplication::translate("MainWindow", "42%", Q_NULLPTR));
        load->setText(QApplication::translate("MainWindow", "425", Q_NULLPTR));
        motor_torq_txt_2->setText(QApplication::translate("MainWindow", "Torque", Q_NULLPTR));
        motor_torq_txt_3->setText(QApplication::translate("MainWindow", "Nm", Q_NULLPTR));
        load_txt_2->setText(QApplication::translate("MainWindow", "Kg", Q_NULLPTR));
        label_6->setText(QString());
        disc_current_txt->setText(QApplication::translate("MainWindow", "Discharge Current", Q_NULLPTR));
        health_txt->setText(QApplication::translate("MainWindow", "Health", Q_NULLPTR));
        label_21->setText(QString());
        label_23->setText(QString());
        duration->setText(QString());
        health->setText(QApplication::translate("MainWindow", "Good", Q_NULLPTR));
        disc_current->setText(QApplication::translate("MainWindow", "42", Q_NULLPTR));
        voltage_text->setText(QApplication::translate("MainWindow", "Voltage", Q_NULLPTR));
        voltage->setText(QApplication::translate("MainWindow", "24V", Q_NULLPTR));
        label_3->setText(QString());
        batt_1->setText(QString());
        batt_2->setText(QString());
        batt_3->setText(QString());
        batt_4->setText(QString());
        batt_5->setText(QString());
        batt_6->setText(QString());
        batt_7->setText(QString());
        batt_8->setText(QString());
        batt_9->setText(QString());
        batt_cap->setText(QString());
        label_7->setText(QString());
        shuffle->setText(QApplication::translate("MainWindow", "s", Q_NULLPTR));
        mute->setText(QApplication::translate("MainWindow", "m", Q_NULLPTR));
        back->setText(QApplication::translate("MainWindow", "<", Q_NULLPTR));
        play->setText(QApplication::translate("MainWindow", "O", Q_NULLPTR));
        forward->setText(QApplication::translate("MainWindow", ">", Q_NULLPTR));
        repeat->setText(QApplication::translate("MainWindow", "r", Q_NULLPTR));
        save->setText(QApplication::translate("MainWindow", "save", Q_NULLPTR));
        remove->setText(QApplication::translate("MainWindow", "-", Q_NULLPTR));
        add->setText(QApplication::translate("MainWindow", "+", Q_NULLPTR));
        currentSong->setText(QApplication::translate("MainWindow", "Song", Q_NULLPTR));
        audio->setText(QString());
        main_window->setText(QApplication::translate("MainWindow", "Main Dashboard", Q_NULLPTR));
        lidar_window->setText(QApplication::translate("MainWindow", "Lidar and Camera", Q_NULLPTR));
        map_window->setText(QApplication::translate("MainWindow", "Map and GPS", Q_NULLPTR));
        battery_window->setText(QApplication::translate("MainWindow", "Battery", Q_NULLPTR));
        sub_main->setText(QString());
        music_window->setText(QApplication::translate("MainWindow", "Music", Q_NULLPTR));
        Engine_window->setText(QApplication::translate("MainWindow", "Engine Traction", Q_NULLPTR));
        date->setText(QApplication::translate("MainWindow", "23-06-2020", Q_NULLPTR));
        clock->setText(QApplication::translate("MainWindow", "20:28:30", Q_NULLPTR));
        sub_engine_status->setText(QApplication::translate("MainWindow", "Engine OK", Q_NULLPTR));
        sub_battery_capacity->setText(QApplication::translate("MainWindow", "50", Q_NULLPTR));
        Electrical_window->setText(QApplication::translate("MainWindow", "Electrical Traction", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
